sfml-app: main.o
	g++  main.o -o sfml-app -L/home/anasty/hangman/graphlib/SFML/lib -lsfml-graphics -lsfml-window -lsfml-system

main.o: main.cpp
	g++ -c main.cpp -I/home/anasty/hangman/graphlib/SFML/include/

